### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by OpossumPetya** [jhthorsen/linkembedder#10]
https://home.thorsen.pm/demo/link-embedder -- the demo doesn't seems to work, just says "fetching".

**Comment by jhthorsen** [comment]
I need to build a new docker image, but it shouldn't take too long to get this out in production.

**Comment by jhthorsen** [comment]
I've moved the demo to a different domain and updated the links in the new release.

https://app.thorsen.pm/linkembedder?url=http://imgur.com/gallery/ohL3e

Thanks for reporting in!
