### ISSUE TITLE
A couple of predefined links in embedder.pl do not work

### ISSUE THREAD

**Issue by OpossumPetya** [jhthorsen/linkembedder#11]
`https://appear.in/link-embedder-demo`
- appear.in is now whereby.com, and I couldn't find a embedder demo on the new site. also don't see embeddable "sare" link on a room, only invites.

`http://paste.scsys.co.uk/557716`
- "Paste not found." , but I guess even if the link is updated it will die after a while anyway.

Also, `imgur.com` links don't open for me, but the image URL is correct, so maybe it's hotlinking to localhost that's being blocked..

**Comment by jhthorsen** [comment]
I think this should be fixed in version 1.07. Please let me know if there are still some issues.

I've added support for some environment variables for the pastebins that expire on time:

```
export TEST_FEDORA=TdDtYw1YSaEDqIOqVYlWbw
export TEST_ONLINE=1
export TEST_PERLBOT=xogtbq
export TEST_SHADOWCAT=586840
```
