### ISSUE TITLE
add an option for the size of video thumbnail

### ISSUE THREAD

**Issue by SvetlanaTkachenko** [jhthorsen/linkembedder#8]
In Convos sharing link to youtube returns an iframe with hardcoded height and width, is this configurable in this module as a parameter? some users find the video thumbnails to be too big.

**Comment by jhthorsen** [comment]
Like I told you on IRC, this can be overridden with CSS.

**Comment by jhthorsen** [comment]
https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

**Comment by SvetlanaTkachenko** [comment]
What I was suggesting is passing the size of the iframe as a parameter in the module. Having a large thumbnail and then reducing its size via CSS is a nice workaround; however, it involves extra work for my computer, which I do not need.

**Comment by jhthorsen** [comment]
It's not a workaround. It's the only way to make sure it works on all screen sizes. You can't do what you suggest and make it work responsively.
